### ISSUE TITLE
Synth snapshot feature

### ISSUE THREAD

**Issue by pachuco** [jwt27/esfm#5]
https://github.com/pachuco/ESSPlayMid/blob/master/src/essfm.h#L5
https://github.com/pachuco/ESSPlayMid/blob/master/src/essfm.c#L43

This seems to be a feature intended for power management use.
But I bet it could be put to good use to see underlying synth structure by comparing snapshots.

**Comment by jwt27** [comment]
Wait - you can *read* from the data port?  I didn't realize that.  That could've made this project a lot easier...

**Comment by jwt27** [comment]
Confirmed, it is possible to read data back.  Thanks!

**Comment by pachuco** [comment]
I was somehow convinced this feature is some magical state save/restore.
But I think not the case.
Just regular FM registry reads and writes.

**Comment by jwt27** [comment]
Ah, yeah, you don't really get more information out than you put in.  But you can see which bits are writable, and that is quite useful.
